turtlebot2: #namespace

    n_actions: 3 # We have 3 actions, Forwards,TurnLeft,TurnRight,Backwards

    speed_step: 1.0 # Time to wait in the reset phases

    linear_forward_speed: 0.5 # Spwwed for ging fowards
    linear_turn_speed: 0.05 # Lienare speed when turning
    angular_speed: 0.3 # Angular speed when turning Left or Right
    init_linear_forward_speed: 0.0 # Initial linear speed in which we start each episode
    init_linear_turn_speed: 0.0 # Initial angular speed in shich we start each episode
    
    hit_reward: 1
    robot_out_of_bounds_penalty: -100 
    ball_out_of_bounds_reward: 100



    

